######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 21 14:10:18 2011
######################################################################

QT += network

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += managent.h testwidget.h
SOURCES += managent.cpp testwidget.cpp
