######################################################################
# Automatically generated by qmake (2.01a) ?? 3? 11 17:12:11 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += network
# Input
HEADERS += main.h
SOURCES += main.cpp
