######################################################################
# Automatically generated by qmake (2.01a) Fri Mar 11 18:58:32 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

QT += network

# Input
HEADERS += mywidget.h
SOURCES += main.cpp mywidget.cpp
