######################################################################
# Automatically generated by qmake (2.01a) ?? 3? 21 17:01:51 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += digitflip.h showpic.h showtext.h showtime.h showvidel.h widget.h
SOURCES += showpic.cpp showtext.cpp showtime.cpp showvidel.cpp widget.cpp
